Getting blog by
PeterKrajci/secret_project pull request #3
Opened 2022-01-11 12:09 UTC by PeterKrajci

Added route for getting blog from DB by ID

2022-01-11 12:49 UTC, mhalajova commented on src/services/blogs.js
> +    const validationResults = validationResult(req);
add new line after this

2022-01-11 12:49 UTC, mhalajova commented on src/services/blogs.js
> +      if (blog == null) {
multiple nested if/else statements are difficult to read. Learn not to nest the code unnecessarily

```
if (!validationResults.isEmpty()) {
    // some code
    return;
}

// some code for retrieving a blog
 if (!blog) {
    // some code
    return;
}

res.status(200).send(blog);
```

2022-01-11 12:49 UTC, mhalajova commented on src/models/blog.js
> +export default { blogModel, blogSchema };
unnecessary export line

2022-01-11 12:49 UTC, mhalajova commented on src/routes/blogs.js
> +    .isLength({ min: 24, max: 24 })
min and max??? isn't it redundant? 
Isnt there function something like `isLength(24)`?

2022-01-11 15:54 UTC, jakubarendac requested changes

2022-01-11 15:54 UTC, jakubarendac commented on src/routes/blogs.js
> +    .isLength({ min: 24, max: 24 })
what is this validation for ? It doesn't make sense from my point of view

2022-01-12 08:26 UTC, PeterKrajci commented on src/routes/blogs.js
> +    .isLength({ min: 24, max: 24 })
In this case the id is automatically generated string that contains letters and numbers.  The length of this string id is fixed, so i think that validating input in this way is not totally bad idea.

2022-01-12 09:02 UTC, merged